name: Docker ECR Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and push Docker image
        run: |
          docker build -t laravel-app:latest .
          docker tag larvel-app:latest 713287342529.dkr.ecr.us-east-1.amazonaws.com/laravel-app:latest
          docker push 713287342529.dkr.ecr.us-east-1.amazonaws.com/laravel-app:latest
